title: Juan David Vargas Mazuera # your name (or website title) here
logo: "/images/Foto_LinkedIn_1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Electronics engineering student with double emphasis in mecatronics and telecommunications. I have great interest in artificial intelligence and finances. I am currently working on a ML software tool to help in buying/selling/holding decissions of stock mid-long term trading in the stock market given companies' intrinsic economic data. 
  <a href="https://www.linkedin.com/in/juan-david-vargas-mazuera-07197a1a5/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
