title: Juan David Vargas Mazuera # your name (or website title) here
logo: "/images/JuanD_33.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Electronics engineering student with double emphasis in mecatronics and telecommunications. I have great interest in artificial intelligence and finaces. I am currently working in ML software tool to help in buying/selling/holding decissions of stock mid-long term trading in the stock market given companies' intrinsic economic data. 
  <br>
theme: jekyll-theme-minimal
